-- Esquema de la base de datos H2 (gestionada por R2DBC)

CREATE TABLE IF NOT EXISTS employees (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    email           VARCHAR(255),
    position        VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS technologies (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS technology_versions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technology_id   BIGINT NOT NULL,
    version         VARCHAR(255) NOT NULL,
    CONSTRAINT fk_version_technology FOREIGN KEY (technology_id) REFERENCES technologies(id)
);

-- Conocimientos tecnológicos de cada empleado
CREATE TABLE IF NOT EXISTS employee_technologies (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     BIGINT NOT NULL,
    technology_id   BIGINT NOT NULL,
    CONSTRAINT fk_emp_tech_employee FOREIGN KEY (employee_id) REFERENCES employees(id),
    CONSTRAINT fk_emp_tech_technology FOREIGN KEY (technology_id) REFERENCES technologies(id)
);

-- Habilidades de cada empleado
CREATE TABLE IF NOT EXISTS employee_skills (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     BIGINT NOT NULL,
    skill           VARCHAR(255) NOT NULL,
    CONSTRAINT fk_skill_employee FOREIGN KEY (employee_id) REFERENCES employees(id)
);

-- Implementaciones funcionales a nivel de software (ej. autenticación JWT)
CREATE TABLE IF NOT EXISTS implementations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(255) NOT NULL,
    description     VARCHAR(4000),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Empleados que han implementado cada funcionalidad
CREATE TABLE IF NOT EXISTS implementation_employees (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    implementation_id   BIGINT NOT NULL,
    employee_id         BIGINT NOT NULL,
    CONSTRAINT fk_impl_emp_implementation FOREIGN KEY (implementation_id) REFERENCES implementations(id),
    CONSTRAINT fk_impl_emp_employee FOREIGN KEY (employee_id) REFERENCES employees(id)
);

-- Etiquetas / palabras clave para buscar implementaciones
CREATE TABLE IF NOT EXISTS implementation_tags (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    implementation_id   BIGINT NOT NULL,
    tag                 VARCHAR(120) NOT NULL,
    CONSTRAINT fk_tag_implementation FOREIGN KEY (implementation_id) REFERENCES implementations(id)
);

-- Tecnologías y versiones usadas en cada implementación
CREATE TABLE IF NOT EXISTS implementation_technology_versions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    implementation_id   BIGINT NOT NULL,
    technology_id       BIGINT NOT NULL,
    version_id          BIGINT NOT NULL,
    CONSTRAINT fk_impl_tech_implementation FOREIGN KEY (implementation_id) REFERENCES implementations(id),
    CONSTRAINT fk_impl_tech_technology FOREIGN KEY (technology_id) REFERENCES technologies(id),
    CONSTRAINT fk_impl_tech_version FOREIGN KEY (version_id) REFERENCES technology_versions(id)
);